# -*- coding: utf-8 -*-
{
    'name': "Real Estate",
    'description': """
        A real World Problem and Solution for Builders and Workers
    """,
    'version': '0.1',
    'summary': '',
    'author': 'Synodica S.O',
    'website': "",
    'sequence': -100,
    'category': 'Real Estate/Brokerage',
    'depends': ['mail', 'web_widget_model_viewer_15', 'board'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'demo/mail_template.xml',
        #'security/security.xml',
        'demo/demo.xml',
        'demo/demo_data.xml',
        'demo/property_demo.xml',
        'views/dashboard.xml',
        # 'views/res_users.xml',     >>> ERROR
        'views/estate_views.xml',
        'views/view_property_type.xml',
        'views/view_property_type_tags.xml',
        'views/estate_offer_view.xml',
        'reports/estate_property_templates.xml',
        'reports/estate_offer.xml',
        'views/estate_menu_view.xml',
        'views/res_user_view.xml',
        'wizard/wizard_validation_form.xml',
        'wizard/valuation_view.xml',
        'views/agent_view.xml',
        'views/agent_language.xml',
    ],
    # 'css':['static/src/css/my_custom_style.css'],
    'demo': [],
    'installable': True,
    'application': True,
    'auto-install': False,
    'licence': 'LGPL-3',
}
